use_frameworks!

target 'DebugModeLogger_Example' do
  pod 'DebugModeLogger', :path => '../'

  target 'DebugModeLogger_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
